image: maven:3.6-ibmjava-8

variables:
  MAVEN_CLI_OPTS: "--batch-mode --settings=/gitlab-runner-m2/settings.xml"
  MAVEN_OPTS: "-Dmaven.repo.local=/gitlab-runner-m2/repository"

cache:
  paths:
    - target/

build:
  stage: build
  script:
    - mvn $MVN_CLI_OPTS compile

test:
  stage: test
  dependencies:
    - build
  script:
    - mvn $MVN_CLI_OPTS test
