image: maven-3-jdk-8:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode -s .m2/settings.xml"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository
    - target/

build:
  stage: build
  script:
    - mvn $MVN_CLI_OPTS compile

test:
  stage: test
  dependencies:
    - build
  script:
    - mvn $MVN_CLI_OPTS test
