#
# Spring Boot Application Configuration
# (https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)
#

# Used by the /info Actuator Endpoint
info:
    app:
        name: Spring Boot Test Application
        description: (This comes from application.yml!)

# Shows what Spring Boot autodetection is actually doing
debug: true

#
# Logging
# (https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html)
#
logging:
    file: spring.log
    level:
        root: INFO
        # This is cool to check which method is called for a specific GET request
        org.springframework.web: DEBUG

server:
    tomcat:
        basedir: tomcat
        accesslog:
            enabled: true

#
# Monitoring using Actuator Endpoints
# (https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-monitoring.html)
# (https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html)
#
#security:
#    user:
#        name: admin
#        password: admin
management:
#    security:
#        role: SUPERUSER
    context-path: /mgmt

endpoints:
    # Show everything if security is used
    sensitive: true
    # It's not a DoS, it's a feature :-)
    shutdown.enabled: true
    