#
# Spring Boot Application Configuration
# (https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)
#

# Used by the /info Actuator Endpoint
info:
    app:
        name: Spring Boot Test Application
        description: (This comes from application.yml!)

# Shows what Spring Boot autodetection is actually doing
debug: true

#
# Logging
# (https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html)
#
logging:
    file: spring.log
    level:
        root: INFO
        # This is cool to check which method is called for a specific GET request
        org.springframework.web: DEBUG
 
 
spring:
    database:
        # driverClassName: org.postgresql.Driver

    datasource:
        platform: h2
        # platform: hsqldb
        # url: jdbc:postgresql://localhost:5432/postgres
        # username: postgres
        # password: postgres
        
    jpa:
        hibernate:
            # naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                globally_quoted_identifiers: false
                # SQL comments are pretty useless
                use_sql_comments: false
                format_sql: true
            hbm2ddl:
                auto: create-drop

            
            